vlm_kwargs:
  min_vram_gb: 19.6
  vlm_id: Qwen/Qwen3-VL-8B-Instruct
  vlm_cls: AutoModelForVision2Seq
  load_in_4bit: False
  torch_dtype: torch.bfloat16
vlm_template:
  image_token: "<|vision_start|><|image_pad|><|vision_end|>"
  prefix: "<|im_start|>system\nYou are a helpful assistant.<|im_end|>\n<|im_start|>user\n{image_token}{question}<|im_end|>\n<|im_start|>assistant\n"