question_postfix: "Answer with Yes or No."
dataset:
  - name: bus-toothbrush
    prompt: "a photo of a bus below a toothbrush"
    qa_pairs:
      - question: "Is the bus below a toothbrush?"
        answer: "Yes"